Update hugo.yml

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -2,34 +2,76 @@ name: Deploy Hugo site to Pages
 
 on:
   push:
-    branches:
-      - main
+    branches: ["main"]
+  workflow_dispatch:
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
+
+defaults:
+  run:
+    shell: bash
 
 jobs:
-  build-deploy:
+  build:
     runs-on: ubuntu-latest
-
+    env:
+      HUGO_VERSION: 0.140.2
     steps:
-      - name: Checkout code
+      - name: Install Hugo CLI
+        run: |
+          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
+          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
+      - name: Install Dart Sass Embedded
+        run: sudo snap install dart-sass-embedded
+      - name: Checkout
         uses: actions/checkout@v3
-
-      - name: Setup Hugo
-        uses: peaceiris/actions-hugo@v2
         with:
-          hugo-version: latest
+          submodules: recursive
+      - name: Setup Pages
+        id: pages
+        uses: actions/configure-pages@v2
+      - name: Install Node.js dependencies
+        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
+      - name: Build with Hugo
+        env:
+          HUGO_ENVIRONMENT: production
+          HUGO_ENV: production
+        run: |
+          hugo \
+            --minify \
+            --baseURL "https://raccoonrampage.ecologygames.eu"
+      # Debug step to inspect the build output
+      - name: Debug Hugo build output
+        run: |
+          echo "Listing contents of the current directory:"
+          ls -R
+          echo "Listing contents of the public directory:"
+          ls -R ./public || echo "Public directory not found"
+      # Upload the public directory as an artifact
+      - name: Upload public directory as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: public
+          path: ./publicc
 
-      - name: Build site
-        run: hugo
-
-      - name: Disable Jekyll
-        run: touch ./public/.nojekyll
-
-      - name: Add CNAME file
-        run: echo "raccoonrampage.ecologygames.eu" > ./public/CNAME
-
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: public
       - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./public
-          force_orphan: true
+        id: deployment
+        uses: actions/deploy-pages@v2
