Update hugo.yml

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -55,8 +55,9 @@ jobs:
           echo "Listing contents of the public directory:"
           ls -R ./public || echo "Public directory not found"
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v1
+        uses: actions/upload-artifact@v4
         with:
+          name: public
           path: ./public
 
   deploy:
@@ -66,6 +67,16 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: public
+
+      - name: Debug public directory after download
+        run: |
+          echo "Listing contents of the public directory:"
+          ls -R ./public || echo "Public directory not found"
+          
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
